version: "3"
services:
  public:
    build:
      context: . 
    env_file:
      - local.env
    ports:
      - "8002:8000"
    volumes:
      - ./trade_remedies_public:/app/
      - ./requirements-dev.txt:/app/requirements-dev.txt
    command: > 
      /bin/sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
