version: "3"
services:
  public:
    build:
      context: . 
    env_file:
      - local.env
    ports:
      - "8002:8000"
    volumes:
      - ./trade_remedies_public:/app/
      - ./trade_remedies_client:/app/trade_remedies_client/
    command: python manage.py runserver 0.0.0.0:8000
