SECURITY_GROUP_ORGANISATION_OWNER = "Organisation Owner"
SECURITY_GROUP_ORGANISATION_USER = "Organisation User"
SECURITY_GROUP_TRA_INVESTIGATOR = "TRA Investigator"
SECURITY_GROUP_TRA_ADMINISTRATOR = "TRA Administrator"

ROLE_APPLICANT = 1
CASE_ROLE_APPLICANT = "Applicant"
CASE_ROLE_RESPONDENT = "Respondent"
