SUBMISSION_TYPE_ADHOC = 3
SUBMISSION_TYPE_EX_OFFICIO = 4
SUBMISSION_TYPE_INVITE_3RD_PARTY = 21
SUBMISSION_TYPE_ASSIGN_TO_CASE = 27
SUBMISSION_TYPE_REGISTER_INTEREST = 7

CASE_DOCUMENT_TYPE_PRESAMPLING_QUESTIONNAIRE = 1
CASE_DOCUMENT_TYPE_LETTER_OF_AUTHORISATION = 2

# Submission types hiding the 'on behalf of' banner
SUBMISSION_TYPE_ALL_ORGANISATIONS = ("interest",)

# flow of submission creation
DIRECTION_BOTH = 0
DIRECTION_PUBLIC_TO_TRA = 1
DIRECTION_TRA_TO_PUBLIC = 2

CASE_TYPE_SAFEGUARDING = 13
CASE_TYPE_REPAYMENT = 11
CASE_TYPE_SAFEGUARD_EXTENSION = 18
CASE_TYPE_SAFEGUARD_SUSPENSION = 19

ALL_COUNTRY_CASE_TYPES = (
    CASE_TYPE_SAFEGUARDING,
    CASE_TYPE_REPAYMENT,
    CASE_TYPE_SAFEGUARD_EXTENSION,
    CASE_TYPE_SAFEGUARD_SUSPENSION,
)

CASE_ROLE_AWAITING_APPROVAL = 9
CASE_ROLE_PREPARING = 11
